### ISSUE TITLE
using Base64 img

### ISSUE THREAD

**Issue by Alexandre-Muzulao** [Remove-Background-ai/rembg.js#3]
I need to use your API with a base64 OR ImgUrl string to remove background images.

Can you do implement this option in your API?

**Comment by mtrabelsi** [comment]
Hi Alexandre, thanks for your report, this feature has been added to 1.1.2, please upgrade your current version. 

https://www.npmjs.com/package/@remove-background-ai/rembg.js/v/1.1.2
